name: macos_system_status_macos
description: MacOS implementation of the macos_system_status plugin
repository: https://github.com/mrasityilmaz/MacOS-System-Status/tree/main/macos_system_status_macos
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-218.0.dev <4.0.0'


flutter:
  plugin:
    implements: macos_system_status
    platforms:
      macos:
        pluginClass: MacOSSystemStatusPlugin
        dartPluginClass: MacOSSytemStatusMacOS


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  macos_system_status_platform_interface: 
    path : '../macos_system_status_platform_interface'


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  very_good_analysis: ^3.0.1
  plugin_platform_interface: ^2.0.0





